### ISSUE TITLE
Infografía RA

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-Yabin-2021#1]
Anexo infografía RA

**Comment by Yabin-2021** [comment]
[T1RA 01 - Infografía RA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-Yabin-2021/files/10922340/T1RA.01.-.Infografia.RA.pdf)

**Comment by MariaC232** [comment]
Calificación = 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
